/*
 * RoxaZip
 * Copyright (c) 2026 RoxaZip contributors
 * License: MIT - see DOC/License-MIT.txt
 */
// Rasterize the editable SVG masters into the existing Windows resource paths.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';

const dir=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(dir,'../..');
const manifest=JSON.parse(fs.readFileSync(path.join(dir,'manifest.json'),'utf8'));
const check=process.argv.includes('--check');
const outputs=[];
const source=name=>fs.readFileSync(path.join(dir,'src',name+'.svg'),'utf8');
const render=(svg,width)=>new Resvg(svg,{fitTo:{mode:'width',value:width},font:{loadSystemFonts:false}}).render();
const iconImage=(entry,size)=>render(source(entry.sizeSources?.[size] || (size===16?entry.source+'-16':size<=32&&entry.smallSource?entry.smallSource:entry.source)),size);
function emit(target,data) {
  const dest=path.resolve(root,target);
  if(!dest.startsWith(root+path.sep)) throw new Error('Output outside repository');
  if(check) {
    if(!fs.existsSync(dest)||!fs.readFileSync(dest).equals(data)) throw new Error(`Stale resource: ${target}`);
  } else {
    fs.mkdirSync(path.dirname(dest),{recursive:true});
    if(!fs.existsSync(dest)||!fs.readFileSync(dest).equals(data)) fs.writeFileSync(dest,data);
  }
  outputs.push(target);
}
function dib(image,ico=false,premultiply=false) {
  const {width:w,height:h,pixels}=image;
  const stride=w*4,maskStride=Math.ceil(w/32)*4;
  const data=Buffer.alloc(40+stride*h+(ico?maskStride*h:0));
  data.writeUInt32LE(40,0); data.writeInt32LE(w,4);data.writeInt32LE(h*(ico?2:1),8);
  data.writeUInt16LE(1,12);data.writeUInt16LE(32,14);data.writeUInt32LE(stride*h,20);
  for(let y=0;y<h;y++) for(let x=0;x<w;x++) {
    const s=(y*w+x)*4,d=40+(h-y-1)*stride+x*4,a=pixels[s+3];
    // resvg exposes premultiplied RGBA. BMP/ImageList needs that as-is;
    // ICO DIB frames store straight BGRA (PNG encoding already handles this).
    const factor=premultiply||a===0?1:255/a;
    data[d]=Math.min(255,Math.round(pixels[s+2]*factor));
    data[d+1]=Math.min(255,Math.round(pixels[s+1]*factor));
    data[d+2]=Math.min(255,Math.round(pixels[s]*factor));data[d+3]=a;
    if(ico&&a===0) data[40+stride*h+(h-y-1)*maskStride+(x>>3)]|=0x80>>(x&7);
  }
  return data;
}
function bitmap(image) {
  const body=dib(image,false,true),header=Buffer.alloc(14);
  header.write('BM');header.writeUInt32LE(14+body.length,2);header.writeUInt32LE(54,10);
  return Buffer.concat([header,body]);
}
function ico(entry) {
  const frames=manifest.sizes.map(size=>{
    const im=iconImage(entry,size);
    return {size,data:size>=64?im.asPng():dib(im,true)};
  });
  const header=Buffer.alloc(6+frames.length*16);
  header.writeUInt16LE(1,2);header.writeUInt16LE(frames.length,4);
  let offset=header.length;
  frames.forEach(({size,data},i)=>{
    const p=6+i*16;
    header[p]=header[p+1]=size===256?0:size;
    header.writeUInt16LE(1,p+4);header.writeUInt16LE(32,p+6);
    header.writeUInt32LE(data.length,p+8);header.writeUInt32LE(offset,p+12);offset+=data.length;
  });
  return Buffer.concat([header,...frames.map(f=>f.data)]);
}
for(const entry of manifest.formats) emit(entry.target,ico(entry));
for(const entry of manifest.applications) {
  const data=ico(entry);
  for(const target of entry.targets) emit(target,data);
}
for(const entry of manifest.toolbars) for(const target of entry.targets) {
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${target.width}" height="${target.height}"><svg x="${(target.width-target.glyphSize)/2}" y="${(target.height-target.glyphSize)/2}" width="${target.glyphSize}" height="${target.glyphSize}" viewBox="0 0 24 24">${source(entry.source).replace(/^[\s\S]*?<svg[^>]*>/,'').replace(/<\/svg>\s*$/,'')}</svg></svg>`;
  emit(target.path,bitmap(render(svg,target.width)));
}
const app=manifest.applications[0];
for(const entry of manifest.package) emit(entry.target,iconImage(app,entry.size).asPng());
emit(manifest.menu.target,bitmap(iconImage(app,manifest.menu.size)));

// Bundled FM must also distinguish formats when there is no external 7z.dll.
// Existing group icons 1 (application) and 100 (About) stay at indices 0 and 1.
const aliases={
  '7z':['7z'],zip:['zip'],rar:['rar'],split:['001'],cab:['cab'],iso:['iso'],
  xz:['xz','txz'],lzma:['lzma','lz','tlz'],lzma2:['lzma2'],tar:['tar'],cpio:['cpio'],
  bz2:['bz2','bzip2','tbz2','tbz'],gz:['gz','gzip','tgz','tpz'],z:['z','taz'],
  liz:['liz'],lz4:['lz4','tlz4'],lz5:['lz5','tlz5'],lzh:['lzh'],lha:['lha'],
  rpm:['rpm'],deb:['deb'],arj:['arj'],vhd:['vhd','vhdx'],wim:['wim','swm','esd'],
  fat:['fat'],ntfs:['ntfs'],dmg:['dmg'],hfs:['hfs'],xar:['xar'],sqfs:['sfs','squashfs'],
  zst:['zst','tzst'],zstd:['zstd','tzstd'],apfs:['apfs'],br:['br']
};
const rc=['// Generated by design/icons/build.mjs. Keep application/About indices 0/1.'];
const associations=[];
manifest.formats.forEach((entry,i)=>{
  rc.push(`${201+i} ICON "../../Archive/Icons/${entry.name}.ico"`);
  for(const ext of aliases[entry.name]) associations.push(`${ext}:${i+2}`);
});
rc.push('','STRINGTABLE','BEGIN',`  100 "${associations.join(' ')}"`,'END','');
emit('CPP/7zip/Bundles/Fm/ArchiveIcons.rc',Buffer.from(rc.join('\n')));

// A compact atlas made from the actual exported sizes, on light and dark surfaces.
const embed=(im,x,y,w=im.width,h=im.height)=>`<image x="${x}" y="${y}" width="${w}" height="${h}" href="data:image/png;base64,${im.asPng().toString('base64')}"/>`;
function preview(dark) {
  const bg=dark?'#1c2129':'#f3f6fa',card=dark?'#272e39':'#ffffff',ink=dark?'#edf3fb':'#202b3a',muted=dark?'#a5b4c5':'#637286';
  let b=`<rect width="1440" height="1430" fill="${bg}"/>`;
  const text=(t,x,y,size=16,color=ink)=>`<text x="${x}" y="${y}" font-family="Segoe UI, sans-serif" font-size="${size}" fill="${color}">${t}</text>`;
  b+=text('RoxaZip',48,64,32)+text('Bound books + leather strap · application / archive / commands',48,96,17,muted);
  b+=`<rect x="40" y="122" width="1360" height="210" rx="16" fill="${card}"/>`;
  for(const [i,e] of manifest.applications.entries()) b+=embed(iconImage(e,96),62+i*178,149)+text(['Application','Install / Setup','Uninstall','Self-extracting'][i],62+i*178,278,15,muted);
  b+=text('Actual pixel sizes',820,164,16,muted);
  let sx=820;
  for(const size of [16,20,24,32,48,64,96]) {b+=embed(iconImage(app,size),sx,248-size)+text(String(size),sx,278,13,muted);sx+=size+18;}
  b+=text('Commands',48,375,22);
  b+=`<rect x="40" y="397" width="1360" height="112" rx="14" fill="${card}"/>`;
  for(const [i,e] of manifest.toolbars.entries()) {
    const svg=source(e.source).replaceAll('#263445',ink);
    b+=embed(render(svg,28),77+i*186,418)+text(e.name,77+i*186,483,15,muted);
  }
  b+=text('Archive formats',48,558,22)+text('Color-coded formats · no text on icons',820,555,16,muted);
  for(const [i,e] of manifest.formats.entries()) {
    const x=40+(i%8)*171,y=581+Math.floor(i/8)*162;
    b+=`<rect x="${x}" y="${y}" width="161" height="151" rx="12" fill="${card}"/>`;
    b+=embed(iconImage(e,64),x+47,y+12)+text('.'+e.name,x+18,y+105,16);
    b+=embed(iconImage(e,16),x+18,y+121)+embed(iconImage(e,24),x+52,y+113)+embed(iconImage(e,32),x+94,y+105);
  }
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="1430">${b}</svg>`;
  return new Resvg(svg,{font:{fontFiles:fs.existsSync('C:/Windows/Fonts/segoeui.ttf')?['C:/Windows/Fonts/segoeui.ttf']:[],loadSystemFonts:true}}).render().asPng();
}
// Preview fonts are presentation-only and do not affect checked resource bytes.
if(!check) {
  for(const theme of ['light','dark']) emit(`design/icons/preview-${theme}.png`,preview(theme==='dark'));
  const cases=[app,...['7z','zip','rar','lzma2','iso'].map(name=>manifest.formats.find(e=>e.name===name))];
  let body='<rect width="1080" height="770" fill="#f3f6fa"/>';
  for(const [i,e] of cases.entries()) {
    const x=12+i*178;
    body+=`<text x="${x+12}" y="32" font-family="Segoe UI" font-size="17" fill="#263445">${e.label || 'RoxaZip'}</text>`;
    for(const [j,size] of [16,24,32].entries()) {
      const y=48+j*236,im=iconImage(e,size);
      body+=`<rect x="${x}" y="${y}" width="164" height="225" rx="8" fill="#fff"/><rect x="${x}" y="${y+65}" width="164" height="160" fill="#272e39"/>`;
      body+=`<text x="${x+8}" y="${y+22}" font-family="Segoe UI" font-size="13" fill="#637286">${size}px / 4x inspection</text>`;
      body+=embed(im,x+12,y+28);
      // Nearest-neighbor enlargement shows the pixels of the actual size.
      body+=`<image x="${x+12}" y="${y+77}" width="${size*4}" height="${size*4}" image-rendering="optimizeSpeed" href="data:image/png;base64,${im.asPng().toString('base64')}"/>`;
    }
  }
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="770">${body}</svg>`;
  emit('design/icons/preview-sizes.png',new Resvg(svg).render().asPng());

  // Review at native sizes rather than enlarged pixels; the full atlas is separate.
  const heroes=[app,...['7z','zip','rar','iso'].map(name=>manifest.formats.find(e=>e.name===name))];
  let overview='<rect width="1000" height="580" fill="#f5f2eb"/>';
  overview+='<text x="34" y="48" font-family="Segoe UI" font-size="28" font-weight="600" fill="#28363f">RoxaZip · BOUND BOOKS</text>';
  overview+='<text x="34" y="77" font-family="Segoe UI" font-size="15" fill="#68737a">Colored volumes / leather strap / silver buckle / no text</text>';
  heroes.forEach((entry,i)=>{
    const x=34+i*194;
    overview+=embed(iconImage(entry,128),x+21,108);
    overview+=`<text x="${x+21}" y="263" font-family="Segoe UI" font-size="18" fill="#28363f">${entry.label || 'RoxaZip'}</text>`;
  });
  overview+='<rect x="20" y="291" width="960" height="269" rx="12" fill="#272e39"/>';
  overview+='<text x="38" y="324" font-family="Segoe UI" font-size="16" fill="#e3e9ef">ACTUAL SIZES</text>';
  [16,24,32,48].forEach((size,row)=>{
    const y=338+row*54;
    overview+=`<text x="38" y="${y+25}" font-family="Segoe UI" font-size="13" fill="#abb8c4">${size} px</text>`;
    heroes.forEach((entry,i)=>{overview+=embed(iconImage(entry,size),155+i*165,y+36-size);});
  });
  emit('design/icons/preview-books.png',new Resvg(`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="580">${overview}</svg>`,{font:{fontFiles:['C:/Windows/Fonts/segoeui.ttf','C:/Windows/Fonts/seguisb.ttf']}}).render().asPng());
}
console.log(`${check?'Verified':'Generated'} ${outputs.length} files (${manifest.formats.length} archive formats, ${manifest.applications.reduce((n,e)=>n+e.targets.length,0)} application ICOs, 14 toolbar BMPs, menu BMP, 3 package PNGs, bundled-format mappings).`);
